name: SkinnyControllers

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core 2
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    
    - name: Setup .NET Core 3
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    
    - name: Setup .NET Core 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Setup .NET Core 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      
    - name: Install dependencies
      run: |
          cd SkinnyControllers
          dotnet restore
          
    - name: Build Skinyy
      run: |
        cd SkinnyControllers
        cd SkinnyControllersCommon
        dotnet build
        dotnet pack  --include-symbols --include-source -o ../Pack
        cd ..
        cd SkinnyControllersGenerator
        dotnet build
        dotnet pack  --include-symbols --include-source -o ../Pack
        
    - name: upload nuget
      uses: actions/upload-artifact@v2.2.1
      with:
        name: NugetPackages
        path: SkinnyControllers/Pack
        retention-days: 1

    - name: Build Aop
      run: |
        cd AOPMethods
        dotnet build
        cd AOPMethodsCommon                
        dotnet pack  --include-symbols --include-source -o ../Pack
        cd ..
        cd AOPMethods
        dotnet pack  --include-symbols --include-source -o ../Pack
        
    - name: upload nuget
      uses: actions/upload-artifact@v2.2.1
      with:
        name: NugetPackages
        path: AOPMethods/Pack
        retention-days: 1
